version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "backend-adham"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-114w1yccniiis"
s3_prefix = "backend-adham"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "DBInstanceIdentifier=\"aws-tests\""
image_repositories = []
