  CognitoEmailConfiguration:
    Type: AWS::Cognito::UserPool EmailConfiguration
    Properties:
      EmailSendingAccount: no-reply@verificationemail.com
      From: Adham Haddad
      ReplyToEmailAddress: adhamhaddad.dev@gmail.com

  CognitoMessageTemplate:
    Type: AWS::Cognito::UserPool InviteMessageTemplate
    Properties:
      EmailMessage: Welcome Friend
      EmailSubject: Signed up succeed

  CognitoUserPoolPasswordPolicy:
    Type: AWS::Cognito::UserPool PasswordPolicy
    Properties:
      MinimumLenght: 8
      RequireLowercase: True
      RequireNumbers: True
      RequireSymbols: True
      RequireUppercase: True

  CognitoUserPoolPolicies:
    Type: AWS::Cognito::UserPool Policies
    Properties:
      PasswordPolicy: !Ref CognitoUserPoolPasswordPolicy

  Cognito:
    Type: AWS::Cognito::UserPool
    Properties:
      AdminCreateUserConfig:
        - AllowAdminCreateUserOnly: True
        - InviteMessageTemplate: !Ref CognitoMessageTemplate
        - UnusedAccountValidityDays: 2
      EmailConfiguration: !Ref CognitoEmailConfiguration
      LambdaConfig: LambdaConfig
      Policies: !Ref CognitoUserPoolPolicies
      UsernameConfiguration: True
      UserPoolName: Admin